### ISSUE TITLE
Batch customer upload functionality no longer working (V3.0.0)

### ISSUE THREAD

**Issue by adamCitrusLime** [brandonseydel/MailChimp.Net#271]
Hi,

I've been working with this package for the last couple of months and got my project to the point where I am able to able to upload a batch of customers to a list.

Since coming back to this project after a couple of weeks, I've found that this functionality no longer works. I've tried to diagnose the issue, the only thing being return is an object reference is null error with the attached stack trace. Is there a relliable way of diagnosing errors being returned from Mailchimp so I am able to resolve my issue?

   at MailChimp.Net.Core.MailChimpException.formatMessage(MailChimpApiError apierror)
   at MailChimp.Net.Core.MailChimpException..ctor(MailChimpApiError apierror)
   at MailChimp.Net.Core.Helper.<EnsureSuccessMailChimpAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailChimp.Net.Logic.BatchLogic.<AddAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at CitrusStore.CitrusStore.MailchimpClasses.VB$StateMachine_16_uploadCustomerDetails.MoveNext() in C:\Websites\clrefsite\CSWeb\Classes\MailchimpClasses.vb:line 224

Thanks,

Adam

**Comment by brandonseydel** [comment]
Let me look into this.

**Comment by adamCitrusLime** [comment]
Hi Brandon,

Thank you for getting back.

The issue I was having is now resolved, it was down to my JSON classes keeling over when I was uploading a large amount of data. I’ve amended my code to account for this.

That being said, I would still be interested to know how I can properly exception data back from the API classes so I would be able to get a better handle on why my program is having issues.

Thanks,

Adam Miles
Product Development Team

citruslime
FRESH RETAIL SOLUTIONS
adam@citruslime.com<mailto:adam@citruslime.com>             [email]

0845 890 1270                           [tel]
0870 706 5088                           [fax]

www.citruslime.com<http://www.citruslime.com/>                [web]

[Description: cid:image001.gif@01CC16CD.2F8D5500]
Head Office :                         Citrus-Lime Limited / Lantern House / The Ellers / Ulverston / LA12 0AA
Manchester Office :               Citrus-Lime Limited / 61 Oxford Street / Manchester / M1 6EQ
Registered Office :                 Citrus-Lime Limited / Lantern House / The Ellers / Ulverston / LA12 0AA

VAT REG Number : 734 7299 05 / Company Number : 03792454

**Comment by brandonseydel** [comment]
Latest code has better error reporting in certain cases.  I will be publishing a new package to nuget soon.
________________________________
