### ISSUE TITLE
MailChimpException can throw an ArgumentException when retrieving exception data

### ISSUE THREAD

**Issue by juliomaqueda** [brandonseydel/MailChimp.Net#593]
`MailChimpException` overrides the `Exception` `Data` field. During the `get` method, an `IDictionary` object is returned, based on the parent's `Data` dictionary plus some extra added entries.

We have observed that, if the parent `Exception` was created from a `SerializationInfo` object containing any of the current data values included in `MailChimpException` (detail, title, type, etc), there is a potential risk of getting an  `ArgumentException`.

Below you can see an actual exception being thrown by this issue in Microsoft's ApplicationInsights library.
```
System.ArgumentException: Item has already been added. Key in dictionary: 'detail'  Key being added: 'detail'
   at System.Collections.ListDictionaryInternal.Add(Object key, Object value)
   at MailChimp.Net.Core.MailChimpException.get_Data()
   at Microsoft.ApplicationInsights.SnapshotCollector.ExceptionExtensions.HasSnapshotContext(Exception ex)
   at Microsoft.ApplicationInsights.SnapshotCollector.ExceptionExtensions.GetSnapshotContext(Exception ex)
   at Microsoft.ApplicationInsights.SnapshotCollector.SnapshotCollectorTelemetryProcessor.ProcessExceptionTelemetry(ExceptionTelemetry exceptionTelemetry)
   at Microsoft.ApplicationInsights.SnapshotCollector.SnapshotCollectorTelemetryProcessor.Process(ITelemetry item)
   ...
```

**Comment by juliomaqueda** [comment]
#592
