### ISSUE TITLE
Newtonsoft.Json version conflicts with version of dependency

### ISSUE THREAD

**Issue by villamike** [brandonseydel/MailChimp.Net#599]
We use Newtonsoft.Json extensively in our application that also includes MailChimp.Net. Our solution has upgraded Newtonsoft.Json to v13.0.2.0 and despite your nuget dependencies indicating v12.0.0 or greater we are receiving the following exception when utilizing the library

**_Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference._**

with the following stack trace
   at MailChimp.Net.Core.Helper.Deserialize[T](Stream stream)
   at MailChimp.Net.Core.Helper.<EnsureSuccessMailChimpAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailChimp.Net.Logic.ApiLogic.<PingAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dovetail.Ecommerce.Module.MailchimpMarketing.Ecommerce.<IsConnected>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dovetail.Ecommerce.Module.MailchimpMarketing.Ecommerce.<UpdateProduct>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

What is the solution path, we simply reference your DLL in the project, do we need to use the code and adjust the references ourselves? 

This is a blocker issue for our next product release which is imminent. Thanks for any insight.

**Comment by brandonseydel** [comment]
Thanks I’ll fix and push soon.
