### ISSUE TITLE
UpdateAsync() in ECommerceStores causing exception errors

### ISSUE THREAD

**Issue by antonyvule** [brandonseydel/MailChimp.Net#601]
When running any UpdateAsync() like for updating products or cart line items, it always returns "A task was canceled" exception errora. Does anyone have the same issue and know how to fix it? But it works with Postman if using the same data. Thank you.

Examples: 

var responseLine = await mailChimpManager.ECommerceStores.Carts(StoreId).Lines(cartId).UpdateAsync(lineId, lineData);
var responseProduct = await mailChimpManager.ECommerceStores.Products(StoreId).UpdateAsync(prodId, prodData);

Exception errors:

System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailChimp.Net.Logic.ECommerceLineLogic.<UpdateAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by duanyunlun** [comment]
I have encountered a similar issue, not only with ECommerceStores, but also with all other UpdateAsync functions (such as Template/Campaign), which will throw this error.

**Comment by duanyunlun** [comment]
The current workaround is that you can change the following in the SendAsync method of MailChimp.Net.Core.MailChimpHttpClient:

From:
```
if (method.Method == "PATCH")
{
request.Headers.ExpectContinue = true;
}
```

To:
```
if (method.Method == "PATCH")
{
request.Headers.ExpectContinue = false;
}
```
