### ISSUE TITLE
Mailchimp calls suddenly throwing exceptions.

### ISSUE THREAD

**Issue by graham83** [brandonseydel/MailChimp.Net#616]
The last few days Mailchimp.NET API calls in my app have started throwing SSL/TLS secure channel exceptions. 

There have been no updates to the OS or .NET App for months that coincide with this. I have restarted the AWS server and verified via Postman that the Mailchimp API is accessible.

Exception is thrown from this call:
`var member = await mc.Members.GetAsync(listId, payerEmail);`

Exception:
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.

I have verified that TLS 1.2 is still enabled on the system - currently set in code via `ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12`

On the app server I have verified in Postman GET  https://us7.api.mailchimp.com/3.0/lists  is still returning 200 OK and the expected lists.  

This is a .NET Framework 4.8 ASP.NET app running on Windows Server 2008 R2  

Full stack trace:

10/19/2023 3:44:25 AM,Error,Void MoveNext()
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailChimp.Net.Logic.MemberLogic.<GetAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PSWebServer.PSLicensingService.<PurchaserLicenseUpdateV3>d__33.MoveNext() in C:\Users\graha\source\repos\PriceSquawk\PSLicensingService\PSLicensingService\PSLicensingService.asmx.cs:line 337
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailChimp.Net.Logic.MemberLogic.<GetAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PSWebServer.PSLicensingService.<PurchaserLicenseUpdateV3>d__33.MoveNext() in 
..PSLicensingService.asmx.cs:line 337

**Comment by graham83** [comment]
Through a heavy ChatGPT debugging session it is almost definitely a cipher issue with the old Windows Server 2008 R2. Closing issue.

**Comment by neilmulhy** [comment]
@graham83 @justinshea I've started having the same error on my Windows 2012 R2 server, running an asp.net Core 3.1 app. It started happening sometime between the 16th 11:30pm - 19th 4:58am October (UK time). 

My code runs fine locally and on a Windows 2019 server, so it's definitely an environment issue.

I thought it was possibly down to MailChimp not accepting non TLS 1.2+ requests, but I've carried out registry edit to enable TLS 1.2 as per:
https://manage.accuwebhosting.com/knowledgebase/3578/How-to-enable-TLS-1-2-on-Windows-2012-Server.html

And I've tried enabling TLS 1.2 in the app:
```
.ConfigureWebHostDefaults(webBuilder =>
{
    webBuilder.UseStartup<Startup>();
    webBuilder.UseKestrel(serverOptions =>
     {
         serverOptions.ConfigureHttpsDefaults(httpsOptions =>
         {
             httpsOptions.SslProtocols = SslProtocols.Tls12;
         });
     });
})
```
Neither of these have solved the issue. If you discover anything else, can you please let me know!

**Comment by justinshea** [comment]
@graham83 @neilmulhy I've attempted to optimize the server TLS ciphers using IIS Crypto to no avail. I've also opened a ticket with MC support but I'm not holding my breath. Thankfully, I've been testing and preparing my app for deployment to server core 2019 and will be accelerating that timeline now..
