### ISSUE TITLE
Importing Members With Addresses

### ISSUE THREAD

**Issue by michaeldinsightly** [brandonseydel/MailChimp.Net#74]
Hey there,

I've run into an issue where if I call the MemberLogic.GetResponseAsync() method and any of the members have an Address type MergeField with any characters in it, an error is thrown. If there is an Address type MergeField but they are all empty, the error is not thrown.

If we call MailChimp's API correctly, they give us valid JSON.

Here is the error:

`Unexpected character encountered while parsing value: {. Path 'members[0].merge_fields.MMERGE3', line 1, position 233.`

```
at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, Encoding effectiveEncoding, IFormatterLogger formatterLogger)
   at System.Net.Http.Formatting.JsonMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, Encoding effectiveEncoding, IFormatterLogger formatterLogger)
   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)
   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.ReadFromStreamAsync(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContentExtensions.<ReadAsAsyncCore>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MailChimp.Net.Logic.MemberLogic.<GetResponseAsync>d__6.MoveNext()
```

**Comment by brandonseydel** [comment]
Can you paste the json you receive from mail chimp.  It looks like address type is returing an unescaped bracket.

**Comment by michaeldinsightly** [comment]
{
	"members": [{
		"id": "91d3a680022d92558d4dc80bd72d59fc",
		"email_address": "michaeltest@redacted.com",
		"unique_email_id": "b9e51adc6e",
		"email_type": "html",
		"status": "subscribed",
		"merge_fields": {
			"FNAME": "Michael",
			"LNAME": "Redacted",
			"MMERGE3": {
				"addr1": "375 S 9th St",
				"addr2": "",
				"city": "San Jose",
				"state": "CA",
				"zip": "95112",
				"country": "US"
			}
		},
		"stats": {
			"avg_open_rate": 0,
			"avg_click_rate": 0
		},
		"ip_signup": "",
		"timestamp_signup": "",
		"ip_opt": "4.15.73.186",
		"timestamp_opt": "2016-08-08T17:04:03+00:00",
		"member_rating": 2,
		"last_changed": "2016-08-08T17:10:00+00:00",
		"language": "",
		"vip": false,
		"email_client": "",
		"location": {
			"latitude": 0,
			"longitude": 0,
			"gmtoff": 0,
			"dstoff": 0,
			"country_code": "",
			"timezone": ""
		},
		"list_id": "18851707c3",
		"_links": [{
			"rel": "self",
			"href": "https://us13.api.mailchimp.com/3.0/lists/18851707c3/members/91d3a680022d92558d4dc80bd72d59fc",
			"method": "GET",
			"targetSchema": "https://us13.api.mailchimp.com/schema/3.0/Lists/Members/Instance.json"
		}, {
			"rel": "parent",
			"href": "https://us13.api.mailchimp.com/3.0/lists/18851707c3/members",
			"method": "GET",
			"targetSchema": "https://us13.api.mailchimp.com/schema/3.0/Lists/Members/Collection.json",
			"schema": "https://us13.api.mailchimp.com/schema/3.0/CollectionLinks/Lists/Members.json"
		}, {
			"rel": "update",
			"href": "https://us13.api.mailchimp.com/3.0/lists/18851707c3/members/91d3a680022d92558d4dc80bd72d59fc",
			"method": "PATCH",
			"schema": "https://us13.api.mailchimp.com/schema/3.0/Lists/Members/Instance.json"
		}, {
			"rel": "upsert",
			"href": "https://us13.api.mailchimp.com/3.0/lists/18851707c3/members/91d3a680022d92558d4dc80bd72d59fc",
			"method": "PUT",
			"schema": "https://us13.api.mailchimp.com/schema/3.0/Lists/Members/Instance.json"
		}, {
			"rel": "delete",
			"href": "https://us13.api.mailchimp.com/3.0/lists/18851707c3/members/91d3a680022d92558d4dc80bd72d59fc",
			"method": "DELETE"
		}, {
			"rel": "activity",
			"href": "https://us13.api.mailchimp.com/3.0/lists/18851707c3/members/91d3a680022d92558d4dc80bd72d59fc/activity",
			"method": "GET",
			"targetSchema": "https://us13.api.mailchimp.com/schema/3.0/Lists/Members/Activity/Collection.json"
		}, {
			"rel": "goals",
			"href": "https://us13.api.mailchimp.com/3.0/lists/18851707c3/members/91d3a680022d92558d4dc80bd72d59fc/goals",
			"method": "GET",
			"targetSchema": "https://us13.api.mailchimp.com/schema/3.0/Lists/Members/Goals/Collection.json"
		}, {
			"rel": "notes",
			"href": "https://us13.api.mailchimp.com/3.0/lists/18851707c3/members/91d3a680022d92558d4dc80bd72d59fc/notes",
			"method": "GET",
			"targetSchema": "https://us13.api.mailchimp.com/schema/3.0/Lists/Members/Notes/Collection.json"
		}]
	}],
	"list_id": "18851707c3",
	"total_items": 1,
	"_links": [{
		"rel": "self",
		"href": "https://us13.api.mailchimp.com/3.0/lists/18851707c3/members",
		"method": "GET",
		"targetSchema": "https://us13.api.mailchimp.com/schema/3.0/Lists/Members/Collection.json",
		"schema": "https://us13.api.mailchimp.com/schema/3.0/CollectionLinks/Lists/Members.json"
	}, {
		"rel": "parent",
		"href": "https://us13.api.mailchimp.com/3.0/lists/18851707c3",
		"method": "GET",
		"targetSchema": "https://us13.api.mailchimp.com/schema/3.0/Lists/Instance.json"
	}, {
		"rel": "create",
		"href": "https://us13.api.mailchimp.com/3.0/lists/18851707c3/members",
		"method": "POST",
		"schema": "https://us13.api.mailchimp.com/schema/3.0/Lists/Members/Instance.json"
	}]
}

**Comment by michaeldinsightly** [comment]
Sorry for the formatting, couldn't get Github to cooperate.

If I put it through jsonlint.com, it returns back a valid JSON string. No missing brackets from what I can tell.

**Comment by michaeldinsightly** [comment]
Hey Brandon,

Just wanted to check in on the status of this. Should we file a ticket with MailChimp?

Best,
Michael

**Comment by brandonseydel** [comment]
It looks like we just need to be string/object for dictionary class

**Comment by NJain27** [comment]
Hi Brandon, I tested that by creating my own member object and making mergeFields Dictionary<string,object> That fixed the problem - would you be able to update that in your code, please?

**Comment by brandonseydel** [comment]
Yes I will be doing this this evening when a new release goes out :)
